# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  test:

services:

  ca_ai.islab.re.kr:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_ai.islab.re.kr
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../build/crypto-config/peerOrganizations/ca_ai.islab.re.kr:/etc/hyperledger/fabric-ca-server
      - ../build/crypto-config/peerOrganizations/ca_ai.islab.re.kr/peers/peer0.ca_ai.islab.re.kr/msp:/etc/hyperledger/fabric/msp
      - ../build/crypto-config/peerOrganizations/ca_ai.islab.re.kr/peers/peer0.ca_ai.islab.re.kr/tls:/etc/hyperledger/fabric/tls
      - ../build/crypto-config/peerOrganizations/ca_ai.islab.re.kr/users:/etc/hyperledger/fabric/users
    container_name: ca_ai.islab.re.kr
    networks:
      - test

  ca_blockchain.islab.re.kr:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_blockchain.islab.re.kr
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../build/crypto-config/peerOrganizations/ca_blockchain.islab.re.kr:/etc/hyperledger/fabric-ca-server
      - ../build/crypto-config/peerOrganizations/ca_blockchain.islab.re.kr/peers/peer0.ca_blockchain.islab.re.kr/msp:/etc/hyperledger/fabric/msp
      - ../build/crypto-config/peerOrganizations/ca_blockchain.islab.re.kr/peers/peer0.ca_blockchain.islab.re.kr/tls:/etc/hyperledger/fabric/tls
      - ../build/crypto-config/peerOrganizations/ca_blockchain.islab.re.kr/users:/etc/hyperledger/fabric/users
    container_name: ca_blockchain.islab.re.kr
    networks:
      - test
  ca_security.islab.re.kr:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_security.islab.re.kr
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../build/crypto-config/peerOrganizations/ca_security.islab.re.kr:/etc/hyperledger/fabric-ca-server
      - ../build/crypto-config/peerOrganizations/ca_security.islab.re.kr/peers/peer0.ca_security.islab.re.kr/msp:/etc/hyperledger/fabric/msp
      - ../build/crypto-config/peerOrganizations/ca_security.islab.re.kr/peers/peer0.ca_security.islab.re.kr/tls:/etc/hyperledger/fabric/tls
      - ../build/crypto-config/peerOrganizations/ca_security.islab.re.kr/users:/etc/hyperledger/fabric/users
    container_name: ca_security.islab.re.kr
    networks:
      - test

  ca_orderer.islab.re.kr:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=orderer.islab.re.kr
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../build/crypto-config/ordererOrganizations/orderer.islab.re.kr:/etc/hyperledger/fabric-ca-server
      - ../build/crypto-config/ordererOrganizations/orderer.islab.re.kr/msp:/etc/hyperledger/fabric/msp
      - ../build/crypto-config/ordererOrganizations/orderer.islab.re.kr/tls:/etc/hyperledger/fabric/tls
      - ../build/crypto-config/ordererOrganizations/orderer.islab.re.kr/users:/etc/hyperledger/fabric/users
    container_name: ca_orderer.islab.re.kr
    networks:
      - test
